# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=http://localhost:5172
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZjg5YTBjOC1kMzZhLTRjMjEtOGRhOS1iYTYxNmYxMzViOTkiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiMzJmMTkyYTUtNTQ4OC00NTg3LWE1NDEtZjhhYTEzZDZjM2E2IiwiZXhwIjoxNzQ0MTczMDAwLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.pGEnDcLE1spiMUWbgomDgi7p1E_MiKjN_xbwE3vGM6s
@hostId=818b9498-fab1-4b0d-8c53-e342b55530f9

POST {{host}}/hosts/{{hostId}}/menus
Content-Type : application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name":"Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}


