# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=http://localhost:5172
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMGViMjJhOC02YjFlLTQ3YjMtYWUyYi1jZTE4MjY4NTgwMDYiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiN2Q3MmE1YWUtOTU0MC00YWMyLTlkYWYtMDVmZjNmNWJkMzE3IiwiZXhwIjoxNzQ0MTg5MjQzLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.p7EdPLJAyOTwMpBzLdTyhSqsnrKJ3y_3HhVmstr-YkI
@hostId=818b9498-fab1-4b0d-8c53-e342b55530f9

POST {{host}}/hosts/{{hostId}}/menus
Content-Type : application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name":"Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}


