GET http://localhost:5172/dinners
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MWE0MzY3My03YzdiLTQzMjUtODEyZS1hYWY5MzUyMDk1ZTgiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiMDIyNWJkZDItN2JhOC00NjM2LWFhOWUtY2YxYTRmMDc3MDc0IiwiZXhwIjoxNzQzNjcyMzQ2LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.aGp32KwCjODgoXnUOtk1jdyPLQG_K0Z4cYhq7BjtrOQ
